UPDATE "Material" SET category = 'Fundație' WHERE category LIKE 'FundaE%';
UPDATE "Material" SET subcategory = 'Cofraj' WHERE "internalCode" = 'STANDARD_PLACAJ_COFRARE';
UPDATE "Material" SET category = 'Fundație' WHERE "internalCode" = 'STANDARD_PLACAJ_COFRARE';
UPDATE "Material" SET subcategory = 'Hidroizolație' WHERE subcategory LIKE 'HidroizolaE%';
UPDATE "Material" SET subcategory = 'Hidroizolație' WHERE subcategory LIKE 'Hidroizola%';
UPDATE "Material" SET category = 'Structură' WHERE category LIKE 'Structur%';
UPDATE "Material" SET subcategory = 'Pereți exteriori' WHERE subcategory LIKE 'PereE>i exteriori';
UPDATE "Material" SET subcategory = 'Pereți interiori' WHERE subcategory LIKE 'PereE>i interiori';
UPDATE "Material" SET category = 'Termoizolație' WHERE category LIKE 'TermoizolaE%';
UPDATE "Material" SET category = 'Finisaje Brute' WHERE category LIKE 'Finisaje brute';
UPDATE "Material" SET category = 'Acoperiș' WHERE category LIKE 'AcoperiE%';
UPDATE "Material" SET subcategory = 'Învelitoare' WHERE subcategory LIKE '%nvelitoare%';
UPDATE "Material" SET subcategory = 'Șapă' WHERE subcategory LIKE '%ap%';
UPDATE "Material" SET subcategory = 'Tencuială' WHERE subcategory LIKE 'Tencuial%';
UPDATE "Material" SET category = 'Tâmplărie' WHERE category LIKE 'T%mpl%rie';
UPDATE "Material" SET category = 'Tâmplărie' WHERE category LIKE 'TAmpla%';
UPDATE "Material" SET subcategory = 'Uși exterior' WHERE subcategory LIKE 'U%i exterior%';
UPDATE "Material" SET subcategory = 'Uși interioare' WHERE subcategory LIKE 'U%i interior%';
